### ISSUE TITLE
Uncaught TypeError: isS is not a function

### ISSUE THREAD

**Issue by onyekachiapam** [ermouth/jQuery.my#13]
Hi,

When I add your js file, It gives an error like that.

Uncaught TypeError: isS is not a function.

Thanks.

**Comment by ermouth** [comment]
Please, read https://github.com/ermouth/jQuery.my#setup and add all dependencies to your page.

**Comment by ArminVieweg** [comment]
Hey, I have added sugar.js but still getting the error. I am inside an options page in a google chrome extension, but I don't get any errors but the mentioned one. This is my head:

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Options page in chrome extension</title>

    <link type="text/css" rel="stylesheet" href="options.css">

    <script type="text/javascript" src="libs/sugar.min.js"></script>
    <script type="text/javascript" src="libs/jquery.min.js"></script>
    <script type="text/javascript" src="libs/jquerymy.min.js"></script>
    <script type="text/javascript" src="libs/handlebars.js"></script>
    <script type="text/javascript" src="options.js"></script>
</head>
```
Thanks!

**Comment by ArminVieweg** [comment]
This error also occures with sugar.js 2.0. So just 1.4 is supported, yet.

**Comment by ermouth** [comment]
You are right, Sugar 2.0 is not supported. 

Number of never announced changes in new Sugar API is enormous https://github.com/andrewplummer/Sugar/blob/2.0.0/CAUTION.md – and gain all those renames give is actually ridiculously small. Sugar 2.0 is just completely other lib, incompatible with 1.4 branch both in general and in details.

I don‘t like it and will remove this dependency in future versions.

So, right now – please, use Sugar 1.4.1.
