### ISSUE TITLE
Bootstap modal popups not working when jquerymy included

### ISSUE THREAD

**Issue by Djumpen** [ermouth/jQuery.my#17]
$('#modal').modal('show') not working on pages with jquerymy (bootstrap 2). Any ideas?

**Comment by ermouth** [comment]
Hi!

$.my have own implementation of modal dlg onboard, and $.my implementation utilizes same namespace. See http://jquerymy.com/ru/api.html#CW-header39 for details.

To avoid naming conflict, you can remove modal functionality from jquerymy.js. Modal is a separate plugin inside, it starts from the line 3445. 

Deleting modal plugin from jquerymy.js does not affect $.my itself.

**Comment by ermouth** [comment]
Reopen to fix. Gonna a) make $.my detect BT on load, b) if BT present, let jQuery.my .modal() guess if params received are Bootstrap-related and pass request through in this case.
