### ISSUE TITLE
multiple select

### ISSUE THREAD

**Issue by tallesdantas** [ermouth/jQuery.my#18]
The multiple select doesnt work with semantcui { http://semantic-ui.com/ }, i think that it also doest work with bootstrap , when i use the $ctrl.select2({}); in init it works but it buggs the layout just working with the select2 api , please help.

**Comment by ermouth** [comment]
> please help

Help to do what?

**Comment by tallesdantas** [comment]
how can i use the multiple select of semantic ui http://semantic-ui.com/modules/dropdown.html with it?, its like bottstrap ,if i use $ctrl.select2({});  it glitchs the layout

**Comment by ermouth** [comment]
Seems to work fine if you create it using conventional `SELECT`, not a bunch of divs. Can you provide a code to reproduce your case?

**Comment by tallesdantas** [comment]
i've tyed to use select too , but when i add a value and cancell it it holds the last one , becouse the default "select multiple(html pure)" aways holds a value, try add multiple values then cancell eatch one.

**Comment by ermouth** [comment]
Well, I see. It‘s indeed a bug. Will fix in 1.2.1 quiet soon, thank for pointing out.

**Comment by tallesdantas** [comment]
thanks, btw nice plugin it's mutch better than downloading a whole library like knowcout, makes me easyer  to program, as soon as you fix it please tellme =D

**Comment by ermouth** [comment]
As a quick fix you can try to add `return $o.val()||[];` right after [line 424 with `}`](https://github.com/ermouth/jQuery.my/blob/master/jquerymy.js#L424) of jquerymy.js. Hope it fix an issue at least in your particular case.

**Comment by tallesdantas** [comment]
Works like a charm , thanks =D

**Comment by ermouth** [comment]
Reopen as a bug to fix into 1.2.1

**Comment by ermouth** [comment]
Fixed in 1.2.1
