### ISSUE TITLE
Event on keydown

### ISSUE THREAD

**Issue by dubrod** [ermouth/jQuery.my#22]
First, awesome plugin, i love it.

I'm doing a dynamic form bind just like your Rockstar death demo.

so i see under `ui > "element" > manifest > ui ` there is 

```
events: "click.my"
```

but it doesnt help much for keyboard accessibility. is there something we can add their for keydown events ?

i even have a jquery .keypress function listening to the `list:` elements so if there is some external command to bind the form that way please let me know.

Thanks!

**Comment by ermouth** [comment]
General approach of $.my is 

1. to simplify coding everyday UI cases, 
2. although keeping thing _somehow_ flexible using declarative markup like `events:[evtList]`, 
3. however allowing maximum flexibility using good old fashoined js code.

So as for your case – put custom bindings into `init` function, placed inside appropriate ui section. Like:

``` javascript
ui:{
  '#ctrl':{
    init: function ($ctrl) {
      var that = this;
      $ctrl.on ('somevent.my', function (evt){
         // Set some filed in data to 1;
         that.data.doc.otherField = 1;
         // Trigger recalc on some other control
         that.my.trigger ('#someOtherCtrl', 'recalc');
      });
    },
    bind:'doc.field'
  }
}
```
Here your control reacts by default and puts/gets its value into `doc.field` when default event happens, although on custom event control does something completely different.

Note, that syntax `somevent.my` with `.my` [namespace](https://api.jquery.com/event.namespace/) guarantees your handler will be automatically unbound on form destroy.

**Comment by dubrod** [comment]
i wish i could say that was the solution but i didnt really understand it. 
**It was helpful though**

It did cause me to rethink the manual trigger i put in. 

I had it looking to the parent b/c the parent had a "manifest ID" i think you call it. but looking at the init you are placing on #ID i re-triggered the keydown for it. 

so...

```
.... if (e.keyCode == 13) {
var target = $(this).children("#id");
target.trigger("click");
}
```

and it loads the form just like a click.
