### ISSUE TITLE
Jquery 3.0 support: .length property instead of .size()

### ISSUE THREAD

**Issue by majorebola** [ermouth/jQuery.my#27]
Seems like JqueryMy uses .size() property.
But in jQuery 3.0 it has been removed (it was deprecated since 1.8)
https://api.jquery.com/size/

I simply tried removing (find-replace) $o.size() with $o.length and it seems to work.
But I'm not at all into jquerymy so I suppose we need more tests.

**Comment by ermouth** [comment]
Good point. Will test approach for 2.x and if everything is ok, put it into 1.2.7.

Thank you.

**Comment by ermouth** [comment]
Applied.
