### ISSUE TITLE
Webpack import $.my() is not a function.

### ISSUE THREAD

**Issue by Sijan117** [ermouth/jQuery.my#31]
Still grasping some fundamentels about webpack, but from what I gather plugin is not being applied on the global jquery? I've tried [expose-loader](https://github.com/webpack/expose-loader) and [imports-loader](https://github.com/webpack/imports-loader) approaches, and also have jquery on my ProvidePlugin object, 

````javascript
plugins: [
        new webpack.ProvidePlugin({
            jquery: 'jquery',
            $: 'jquery',
            jQuery: 'jquery',
            "window.jQuery": 'jquery',
            "Tether": 'tether',
            "window.Tether": 'tether'
        })
    ],
`````

to no avail. 

Can there be some instructions or suggested method of using this plugin with webpack in the docs?

**Comment by Sijan117** [comment]
I was actually misusing the expose-loader, removing the plugins block from my webpack config and appending, 

````javascript
            {
                test: require.resolve('jquery'),
                loaders: ['expose?$', 'expose?jQuery']
            },
````
solved this issue.

**Comment by ermouth** [comment]
Nice!

Can you please provide entire resulting config or whatever to help respond future questions of this kind? I have nearly zero experience with webpack, any information is valuable.

Thanks )

**Comment by Sijan117** [comment]
yeah for sure man, in full disclosure i'm also just starting out with webpack so while this setup does work, I can't guarantee that it is best, or recommended, approach. 

The following is using

- webpack 2.1.0-beta.21
- jquery 3.1.0
- jquerymy 1.2.7 

as far as the config goes, (and from what I gather this [applies](https://65535th.com/jquery-plugins-and-webpack/) to a large portion of jQuery plugins), assuming you have webpack setup in your project directory, you'll need the [expose-loader](https://github.com/webpack/expose-loader), 

```javascript 
npm i expose-loader -D
``` 

the rest of the configuration is unimportant, save for the part I mentioned before, as described on the expose-loader github page, you'll need to have this: 

```javascript 
//webpack.config.js
module.exports = { 
    ....
    module: {
        loaders: [ 
            ....
            {
                test: require.resolve('jquery'),
                loaders: ['expose?$', 'expose?jQuery']
            },
            ....
        ]
    }
    ....
};
```

That took care of all jqeury issues in my case. 
However, I will also mention that even though node installed the recommended version of sugar (1.4.1) I still encountered #13 . The only way I found around this was to  

```javascript 
import 'sugar';  // require('sugar'); if not using ES6
```

In my main entry point, this will resolve to the version of sugar installed automatically by npm when installing jquerymy. Webpack usually takes care of this stuff, I might have missed something, but anyways, it worked. 

If anyone with further insight into webpack has anything to share, please do, and I hope this helps someone in the future.

**Comment by ermouth** [comment]
You made perfect work, thanks!

> I still encountered #13 . The only way I found around this was to

I will look into it more deeply.
