### ISSUE TITLE
isS is not a function

### ISSUE THREAD

**Issue by juanbaby2015** [ermouth/jQuery.my#37]
jquery v1.12.4 my.js 1.2.0

**Comment by ermouth** [comment]
1. Please, use latest jquerymy.js, that is 1.2.7
2. Read http://jquerymy.com/api.html#CW-quick-star and make sure you have Sugar.js 1.4.1 loaded.

Comments in issues https://github.com/ermouth/jQuery.my/issues/13 and https://github.com/ermouth/jQuery.my/issues/31 might be helpful.
