### ISSUE TITLE
Issue with browser autocomplete forms

### ISSUE THREAD

**Issue by gopal-g** [ermouth/jQuery.my#41]
The data autofilled by browser like chrome auto-fill is not being read by the plugin unless the input fields are focused or touched.

**Comment by ermouth** [comment]
Actually they are read normally. If they are not, you probably changed events list for a control so it does not track `input` and `change` events, which are vital for that kind of tracking.

Also there exist Chrome plugins, often of malicious nature, that block propagation of those events. Hope it‘s not your case.

If you think there is another reason, please provide more detailed info: browser ver, platform, type of controls you feel are failing and so on. Best way is to provide a gist with a code snippet.
