### ISSUE TITLE
Validation error message not working on custom validation function

### ISSUE THREAD

**Issue by silentw** [ermouth/jQuery.my#42]
As you can see in my example, if I use a regexp to do the check, it shows the correct error message.

However, if I use a custom function, it simply returns an general "Error".

[DEMO](http://jsbin.com/datuteruvi/1/edit?html,css,js,output)

Hope you understand what I'm asking. Thanks.

**Comment by silentw** [comment]
`return !/^\S{3}.*$/i.test(value) ? '3+ chars please' : '';`

**Comment by ermouth** [comment]
> to return the error message on the function itself

Right. However, good catch. I‘ll rethink `check` fn behavior for returning non-strings with `error` present.
