### ISSUE TITLE
isS is not a function

### ISSUE THREAD

**Issue by TBRickYoung** [ermouth/jQuery.my#43]
I'm having the same issue as others while trying to load jQuery.my.js
Below is the loading order. I have tried a lot a ways to load but keep getting the same error.
![image](https://user-images.githubusercontent.com/11824898/32250629-8b149678-be4a-11e7-8c66-843464ca6420.png)

'web/webroot/_ui/responsive/global/js/responsive-global-header.js': [
                        ui_src_responsive + '/global/js/sugar/sugar.min.js',
                        ui_src_responsive + '/global/js/jquery-3.1.1.min.js',
                        ui_src_path + 'sourceFiles/js/blazy.min.js',
                        ui_src_responsive + '/global/js/jquery-ui-1.12.1.min.js',
                        ui_src_responsive + '/global/js/jquery.cookie-1.4.1.js',
                        ui_src_responsive + '/global/js/coffee-script-1.6.3.js',
                        ui_src_responsive + '/global/js/jquerymy/jquerymy.js',

Thanks!

**Comment by ermouth** [comment]
I can’t locate anything like regexp from screenshot in jquerymy code, so problem is definitely outside jquerymy. 

Since isS definition is clearly inside jquerymy, and it’a a shortcut for Object.isString() from Sugar, I think sugar.js failed to initialize, but Sugar also have nothing like that regexp inside.

The regexp is not only invalid, but very strange looking, so I think web server you use sends at least sugar.js with invalid encoding (mb 8859 instead of UTF-8), or invalid mime type (text/plain instead of text/javascript), or both. Please, check it out.

Also encoding tricks in regexp may appear due to very special combination of params of some js compressors/transformers, however it‘s much less likely.

**Comment by ermouth** [comment]
@TBRickYoung please, let me know if you was able to solve the issue.

**Comment by TBRickYoung** [comment]
Yes, I was able to. It was document type. I had to down load the js and run it through a couple tools to get it to work. But I do have a question for you. We would like to have a class name that will attach to everything with that class name like .product-qty but we had to set one for each class like .product-qty-0 and .product-qty-1. With the .my handle arrays like jQuery for classes?

Here is what we did to bind the product qty input to the price-set which then watches for both product-qty-0 and product-qty-1 this works but we have pages where we want to have lots of dynamic product-qty which will goto the price-set function.

$(".productPrice").my({
    ui:{
        ".product-qty-0": {
            bind: function(data, value, $control){

                // check to see if the value is a number only
                var regExp = /^\d*$/;
                var productQty = $control.val();

                var maxQty = dataStore.products[0].maximumQuantity;
                var minQty = 1;

                if(dataStore.page.productType == "lawn") {
                    maxQty = 99;
                    // set error message text to 99
                    $(".max-qty").text(maxQty);
                }
                if (value){

                    if (regExp.test(value)) {
                        if (productQty < minQty) {
                            productData[0].price.qty = minQty;
                            $control.val(minQty);
                        }else if (productQty > maxQty){
                            productData[0].price.qty = maxQty;
                            $control.val(maxQty);
                        }else{
                            productData[0].price.qty = productQty;
                            $control.val(productQty);
                        }
                    }else{
                        productData[0].price.qty = minQty;
                        $control.val(minQty);
                    }
                }

            },
            events: "keyup.my"
        },
        ".product-qty-1": {
            bind: function(data, value, $control){

                // check to see if the value is a number only
                var regExp = /^\d*$/;
                var productQty = $control.val();

                var maxQty = dataStore.products[1].maximumQuantity;
                var minQty = 1;

                if(dataStore.page.productType == "lawn") {
                    maxQty = 99;
                    // set error message text to 99
                    $(".max-qty").text(maxQty);
                }

                if (value){

                    if (regExp.test(value)) {
                        if (regExp.test(value)) {
                            if (productQty < minQty) {
                                productData[1].price.qty = minQty;
                                $control.val(minQty);
                            }else if (productQty > maxQty){
                                productData[1].price.qty = maxQty;
                                $control.val(maxQty);
                            }else{
                                productData[1].price.qty = productQty;
                                $control.val(productQty);
                            }
                        }
                    }else {
                        productData[1].price.qty = minQty;
                        $control.val(minQty);
                    }
                }

            },
            events: "keyup.my"
        },
        ".price-set": {
            bind: function(data, value, $control) {

                var totalQty = 0;
                if (pageData.isStaggered) {
                    totalQty = parseInt(productData[0].price.qty) + parseInt(productData[1].price.qty);
                    console.log("productData[0].price.qty="+productData[0].price.qty+"  |  productData[1].price.qty="+productData[1].price.qty+"  |  $control.val()="+$control.val());

                }else{
                    totalQty = parseInt(productData[0].price.qty);
                    console.log("productData[0].price.qty="+productData[0].price.qty+"  |  $control.val()="+$control.val());

                }

                //This is where we update the text field with the appropriate total items and pricing for the .price-set element
                __COMPONENT_UID__.pricingPanel.updateProductPrice();

                // Check qty to disable/enable button
                __COMPONENT_UID__.pricingPanel.validateQty(totalQty);

                // Check to see if MIR avaiable based on Qty
                __COMPONENT_UID__.pricingPanel.updateMIR(totalQty);

            },
            watch: ".product-qty-0, .product-qty-1"
        }
    }
}, productData);


Thanks!


Rick

**Comment by ermouth** [comment]
In short, you should make repeated child form list and bind it to an array, see http://jquerymy.com/api.html#CW-repeated-c. If you want some kind of total field, make it watch your entire list and update on list update.

Smth like:
``` javascript
({
  init:'<div id="rows"></div><div id="total"></div>',
  data:{rows:[{value:1}, {value:2}, {value:3}], total:0},
  ui:{
    '#rows':{
      bind:'rows',
      list:'<div><input type="number" class="row"></div>',
      manifest:{
        ui:{
          '.row':'value'
        }
      }
    },
    '#total':{
      bind:function(d){
        return d.rows.map(function(elt){return +elt.num}).sum();
      },
      watch:'#rows'
    }
  }
})
```
Closing issue.

**Comment by TBRickYoung** [comment]
OK, I will try that out. Thanks again for the fast response!

Rick
