### ISSUE TITLE
Support binding for inputs of type "tel" and "email"

### ISSUE THREAD

**Issue by mrmusselman1-andculture** [ermouth/jQuery.my#45]
Could you please add support for both `input[type="tel"]` and `input[type="email"]`?

Modification would occur at line 319 as follows: 
```
"[type='text'],[type='number'],[type='search'],[type='hidden'],[type='password'],[type='button'],[type='range'],[type='tel'],[type='email'],:not([type])":{
```
https://github.com/ermouth/jQuery.my/blob/5bce4a06bb452b6d63afb2321dbc9f51ce430af4/jquerymy.js#L319

**Comment by ermouth** [comment]
Good point, I’ll add both types on weekend.

**Comment by mrmusselman1-andculture** [comment]
Thank you! I love this plugin!
