### ISSUE TITLE
Detecting change in linked field

### ISSUE THREAD

**Issue by andreyuv** [ermouth/jQuery.my#47]
Hi,

This is a simplified version of what I'm trying to accomplish, in order to discuss it more easily.

I linked two fields using jQuery.my. Then I listen to changes on the first field and run an action when the change event fires.

The change event doesn't fire when the first field is updated by writing in the second field.
I feel like there would be a way to do this using jQuery.my, but after reading the documentation it's not very clear to me how to proceed.

Here is an example on CodePen: https://codepen.io/andreyu/pen/GBrpbj

```
<h2>Form</h2>
<form action="" id="form">
    <div><input id="name" type="text" placeholder="Name" value="Anna" /></div>
</form>

<h2>Form 2:</h2>
<form action="" id="form2">
    <div><input id="name2" type="text" placeholder="Name" /></div>
</form>

<br><br>

<script type="text/javascript">
    
    // Init $.my over DOM node
    $("body").my({
        
        // Init function
        init: function ($node, runtime) {
        },
        
        // Bindings
        ui: {
            "#name": {bind: "name", watch: "#name2"},
            "#name2": {bind: "name", watch: "#name"}
        }
    });
    
    $("#name").on("change",function() {
       alert("name changed");
    });
    
</script>
```

In this example I would like an alert() to fire when writing in the second field.

Thank you for your time.

**Comment by ermouth** [comment]
> listen to changes

Actually you are listening to the `change` event, which is not fired this case. It is only fired on direct user interactions, according to https://developer.mozilla.org/en-US/docs/Web/Events/change.

So to track changes from both fields you better add third field, say, `<div id="alerter"></div>`, and use it as a collector, which may call external code. Please note it will be activated multiple times.

```
{
  "#name": {
    bind: "name", 
    watch: "#name2"
  },
  "#name2": {
    bind: "name", 
    watch: "#name"
  },
  '#alerter':{
    bind: function(d,v){
      if(v==null) console.log('Name is '+d.name)
    },
    watch:['#name','#name2']
  }
}
```

Hope it helps.

**Comment by andreyuv** [comment]
Thank you for your quick and helpful reply!
