### ISSUE TITLE
Dependency on SugarJS

### ISSUE THREAD

**Issue by mmariano** [ermouth/jQuery.my#5]
This library looks really great! I think the big selling point is how we can get data binding but not have to signup for some bigger framework. However SugarJS is very intrusive and modifies natives. Unfortunately that means using this library ends up touching all parts of core javascript. Which is not something that I can sign up for in existing apps. If you could somehow disconnect yourself from this library (maybe use underscore?) I think that would really be helpful. 

I understand this is technically not an issue. But I just wanted to bring it up. Thanks.

**Comment by ermouth** [comment]
> disconnect yourself from this library (maybe use underscore?)
Undescore is a) more fat, b) less fast in several cases, c) will produce less readable code, d) need retirement or thorough re-testing of all existing code my clients use. 

So do not think its possible right now.
