### ISSUE TITLE
does it support a grandson list form?

### ISSUE THREAD

**Issue by fjnalhm** [ermouth/jQuery.my#56]
Hello,
    seems that it doesn't work when I bind a child list form B with another child list form A.
Form A works well, but the form B cannot excute 'insert' or 'remove'.
And I also found that there is not a 'my-form-xxxx' class property in form B.

Tks for reading, expecting your reply.

**Comment by ermouth** [comment]
Please provide sample code.

**Comment by fjnalhm** [comment]
Form B works well now. 
I maked a mistake with the keyword 'manifest', type as 'mainfest'.
