### ISSUE TITLE
Destroy?

### ISSUE THREAD

**Issue by tmikaeld** [ermouth/jQuery.my#6]
Is there any way to destroy an instance?

I'm using .my in an admin panel and it works amazingly, but performance starts to be an issue after a few instanced forms. I'd rather load it on request and remove it when the editing modal is closed.

**Comment by ermouth** [comment]
http://jquerymy.com/en/api.html#CW-runtime-co

$form.my("remove")

**Comment by tmikaeld** [comment]
Darn it, i searched every page for destroy when i should have looked for remove ;-)

Thanks!

**Comment by ermouth** [comment]
Good point although, I must mention form disband in more clear way.

**Comment by tmikaeld** [comment]
That would be nice, other than this i love your documentation and samples. 

Before this i have been avoiding two-way binding, but the way you are explaining it and doing it is very very sexy - and it melts like butter into my current project code!
