### ISSUE TITLE
Repeated sections: can add new element unless user interacts with the control

### ISSUE THREAD

**Issue by danielo515** [ermouth/jQuery.my#9]
Hello,

First of all thank you for this awesome library. It helps a lot to people like me, with any sense of organizing and setting it's own coding-rules (dash or underscore? or maybe camel case? arrays or objects as return? and a long list...)

I'm facing a small problem that I don't know if it is intentional, and if it is I wanna know how to avoid it. It is about repeated sections, I mean, child forms, nested forms or however you prefer to call it. I have a button which is binded to a function that triggers the "insert" method of the container binded to the array that holds the repeated section. Each time I click on the button I have to interact with the newly added control (is a text area) to be able to add another element to the list. If I click the button twice, nothing happens. Why? I though it was intentional on some examples (specifically coded for that) but seems to be the default behavior for everything. Could you help me? this makes my application very uncomfortable to use. 

Thanks in advance

**Comment by danielo515** [comment]
oK, I found the solution.

 You have to pass the insert method an object, indicating what to insert, and optionally where. To be honest I'm not sure what properties are mandatory and what parts are not. Can I provide just the where property?

For those interesthed, this is how the call sholud look like:

```
.trigger ("insert",{ what:{name:"Col"+data.columns.length},where:1e6});	
```

This is a bit un-intuitive and it should be mentioned in docs at some place.
PD: What the hell 1e6 means?
Regards

**Comment by ermouth** [comment]
> This is a bit un-intuitive and it should be mentioned in docs at some place.

It is mentioned – http://jquerymy.com/api.html#CW-repeated-c. Please, use API reference at the project‘s site, not Github version. Github version is not full – it‘s rather hard to maintain all three versions of docs, especially taking in account Github does not allow code snippets. Thats why I specially pointed at the start of Github one, that there exist more detailed API ref.

Both `what` and `where` are optional. `1e6` is position where to insert, large nums insert at the end of list.

> First of all thank you for this awesome library. 

Thank you )

**Comment by ermouth** [comment]
To add – you can insert section using jQuery syntax, see http://jquerymy.com/api.html#CW-controls-c

**Comment by danielo515** [comment]
Hello @ermouth 

I was reading the docs page of jquerymy.com. And I read that section. But there is no clear reference on it about the fact that if you do not specify what to insert, then nothing is inserted. The only thing that makes you think that is this sentence .
>Sparse arrays are not supported, so {where:1e6} inserts row at the end of the list.

I did not know what sparse arrays are, so I searched it. Sparse arrays are arrays with identical values appearing more than once, so I guess that if you try to insert an empty object and there is already one, then you are not allowed to insert it. Please correct me if I'm wrong. The problem is that, if you don't understand that term (I'm not native English), you will not even think that it is the key of your problem.

I also want to thank and congratulate you for cloudwall, another awesome piece of software. It reminds me (in some way) to [tiddlywiki](http://www.tiddlywiki.com). Is there any mailing list or official forum? (sorry for hijacking this ticket, but I did not want to open another one just for this)

Thank you.

**Comment by ermouth** [comment]
Just read Wiki about sparse array – definition is surely bit confusing. Sparse array for JS is an array, where some indexes has no value (`undefined`). Like:

```javascript
var a = []; a[0] = 1; a[100]=2;
```

I‘ll improve manual to make it more clear, thanks for pointing it out. Is formulae `Each member of an array must be an object, and it‘s a good practice to make each member unique` is more clear?

Also I gonna describe `.where` property more precisely.

>  if you do not specify what to insert, then nothing is inserted

 Also good point. In fact in this case $.my inserts `.data` section of a default child manifest, if any.

> Is there any mailing list or official forum [for cloudwall]?

No, not yet. It‘s not so popular ) In fact, I do not want to propagate cloudwall widely right now. Reason is default underlying low-level storage (IDB) is full of bugs in Chrome. Moreover, guys from Chrome add new bugs in literally every major release. Yes, thay fix old bugs – but add new ones ((( It sometimes cause severe errors and even attachments loss if you are not synced with remote CouchDB.

So I just don‘t want to be responsible for Google bugs.

Surely, guys from PouchDB (lib inside cloudwall that converts IDB to more robust and syncable storage) fight with Chrome IDB bugs more or less successfully. Nevertheless I do not want to propagate software, that can accidentally discard user‘s data after browser update. Hate Chrome and IDB for this, especially taking in account IDB is born inside Google.

In fact, cloudwall.me is much more reliable (and sometimes more fast!) in Safari+WebSQL on iPad for example, then in Chrome.

So please, be patient. I see growing pressure on Chrome team from community, so I think they‘ll be more inspective testing IDB before releasing new versions of Chrome.

> I'm not native English

I‘m also not.

**Comment by danielo515** [comment]
>var a = []; a[0] = 1; a[100]=2;
I‘ll improve manual to make it more clear, thanks for pointing it out. Is formulae Each member of an array must be an object, and it‘s a good practice to make each member unique is more clear?

Yes, it is more clear. Thank you very much.

> Also I gonna describe .where property more precisely.

Good idea

>if you do not specify what to insert, then nothing is inserted
>>Also good point. In fact in this case $.my inserts .data section of a default child manifest, if any.
Yes, it inserts it first time, until you click it again. Then nothing happens.

Now I'm feel lucky of using cloudwall in Firefox!!!
And is there any  mailing list or something similar for jquerymy? I'm experiencing some problems with modals and I would love to ask about it.

**Comment by ermouth** [comment]
> Yes, it inserts it first time, until you click it again. Then nothing happens.

Because you‘re trying to create a full duplicate – $.my can not distinguish duplicates and assume it‘s a single item. If you modify already inserted item somehow and then insert new one – it must appear.

Good approach is to add something like `id` property into child section and put `Date.now()` into it to guarantee you have no dups even if you did not modified item.

> And is there any mailing list or something similar for jquerymy?

No, sorry, and I do not plan to. Feel free to raise new issues here, but please label them as `question` if it‘s a question.
